version: "3.8"

services:
  mongo:
    image: mongo:3.6.21
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
